services:
  db:
    container_name: postgresql_db
    image: postgres:16-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=steven
      - POSTGRES_PASSWORD=steven
      - POSTGRES_DB=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -U postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db: {}
  