# Generated by Django 5.1.2 on 2024-10-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('stop', models.TimeField()),
                ('ids', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.ManyToManyField(related_name='friday', to='app.timeslot')),
                ('monday', models.ManyToManyField(related_name='monday', to='app.timeslot')),
                ('saturday', models.ManyToManyField(related_name='saturday', to='app.timeslot')),
                ('sunday', models.ManyToManyField(related_name='sunday', to='app.timeslot')),
                ('thursday', models.ManyToManyField(related_name='thursday', to='app.timeslot')),
                ('tuesday', models.ManyToManyField(related_name='tuesday', to='app.timeslot')),
                ('wednesday', models.ManyToManyField(related_name='wednesday', to='app.timeslot')),
            ],
        ),
    ]
